version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_TRAEFIK: "${MOODLE_DOCKER_TRAEFIK}"
      MOODLE_DOCKER_TRAEFIK_HTTPS: "${MOODLE_DOCKER_TRAEFIK_HTTPS}"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=local-proxy"
      - "traefik.http.routers.${MOODLE_CODENAME}.rule=Host(`${MOODLE_CODENAME}.astons.dev`)"
      - "traefik.http.routers.${MOODLE_CODENAME}.tls=true"
      #- "traefik.http.services.${MOODLE_CODENAME}.loadbalancer.server.port=80"
    networks:
      - default
      - local-proxy
  exttests:
    networks:
      - default
      - local-proxy
  selenium:
    networks:
      - default
      - local-proxy

networks:
  local-proxy:
    external: true
